site_name: Wave wet en regelgeving

theme:
  name: material
  langueage: en
 
# Copyright
copyright: Copyright Â© 2023 - 2024 Wave Testserver

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
